### ISSUE TITLE
Error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small

### ISSUE THREAD

**Issue by setube** [VickScarlet/lifeRestart#124]
root@DMIT-ypbWyMjjCt:/www/wwwroot/8000# anywhere
_tls_common.js:129
      c.context.setCert(cert);
                ^

Error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
    at Object.createSecureContext (_tls_common.js:129:17)
    at Server.setSecureContext (_tls_wrap.js:1330:27)
    at Server (_tls_wrap.js:1185:8)
    at new Server (https.js:74:3)
    at Object.createServer (https.js:110:10)
    at Object.<anonymous> (/www/server/nvm/versions/node/v14.17.6/lib/node_modules/anywhere/bin/anywhere:131:7)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  library: 'SSL routines',
  function: 'SSL_CTX_use_certificate',
  reason: 'ee key too small',
  code: 'ERR_SSL_EE_KEY_TOO_SMALL'
}

**Comment by jingyuexing** [comment]
目前看来，是SSL的密钥太小了，所以SSL报错，证书的原因吧

**Comment by TimesWhite** [comment]
对不起，我不在，我登陆了会尽快回复。
