### ISSUE TITLE
webpack-cli ERROR：Unexpected token =

### ISSUE THREAD

**Issue by cleverlion** [VickScarlet/lifeRestart#176]
When starting the project，webpack-cli throws an error：
SyntaxError: Unexpected token =

The configuration in the .babelrc  file is:
`{
  "presets": [
    ["env", { "modules": false }],
    "stage-2",
    "es2015"
  ],
  "plugins": ["transform-runtime"],
  "comments": false
}
`

`[webpack-cli] D:\lifeRestart\my-project\node_modules\webpack-dev-server\lib\servers\WebsocketServer.js:10
  static heartbeatInterval = 1000;
                           ^

SyntaxError: Unexpected token =
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (D:\lifeRestart\my-project\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
    at Module._compile (D:\lifeRestart\my-project\node_modules\v8-compile-cache\v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (D:\lifeRestart\my-project\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Server.getServerTransport (D:\lifeRestart\my-project\node_modules\webpack-dev-server\lib\Server.js:982:28)`

**Comment by jayzun** [comment]
webpack-dev-server使用了新的定义class成员的语法，你可以升级你的node版本试试

**Comment by cleverlion** [comment]
> webpack-dev-server使用了新的定义class成员的语法，你可以升级你的node版本试试

好的谢谢

**Comment by g1un** [comment]
Just translated @jayzun answer, it helped me.
webpack-dev-server uses a new syntax to define class members,you can upgrade your node version to try

**Comment by jadeshenker** [comment]
@g1un what version did you need to update to?

**Comment by rubangarmon** [comment]
Same problem. I'm using webpack serve --config ./webpack.config.ts

**Comment by joergkrause** [comment]
Definitely upgrading NodeJs helps. The static variables syntax is available in Node 6, but the static class variable that's used here is available in Node 12.6. Going to the latest LTS is recommended to solve the issue.
